# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3e078004acc95fe018f6db932904d58"
name = "rg-products-quick-editor"
handle = "rg-products-quick-editor"
application_url = "https://kazakhstan-bulletin-seq-declined.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "themedemo1003.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_inventory,write_locations,write_orders,write_products"

[auth]
redirect_urls = [
  "https://kazakhstan-bulletin-seq-declined.trycloudflare.com/auth/callback",
  "https://kazakhstan-bulletin-seq-declined.trycloudflare.com/auth/shopify/callback",
  "https://kazakhstan-bulletin-seq-declined.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
